# Generated by Django 2.2.4 on 2019-08-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190809_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
