# Generated by Django 2.2.4 on 2019-08-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
